/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val { byte | mask } else { byte & !mask }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if self.get_bit(i + bit_offset) {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        let mut val = 0;
        for i in 0..(bit_width as usize) {
            if unsafe { Self::raw_get_bit(this, i + bit_offset) } {
                let index = if cfg!(target_endian = "big") {
                    bit_width as usize - 1 - i
                } else {
                    i
                };
                val |= 1 << index;
            }
        }
        val
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < self.storage.as_ref().len());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= self.storage.as_ref().len());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            self.set_bit(index + bit_offset, val_bit_is_set);
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        debug_assert!(bit_width <= 64);
        debug_assert!(bit_offset / 8 < core::mem::size_of::<Storage>());
        debug_assert!((bit_offset + (bit_width as usize)) / 8 <= core::mem::size_of::<Storage>());
        for i in 0..(bit_width as usize) {
            let mask = 1 << i;
            let val_bit_is_set = val & mask == mask;
            let index = if cfg!(target_endian = "big") {
                bit_width as usize - 1 - i
            } else {
                i
            };
            unsafe { Self::raw_set_bit(this, index + bit_offset, val_bit_is_set) };
        }
    }
}
pub const DRFLAC_VERSION_MAJOR: u32 = 0;
pub const DRFLAC_VERSION_MINOR: u32 = 13;
pub const DRFLAC_VERSION_REVISION: u32 = 4;
pub const DRFLAC_TRUE: u32 = 1;
pub const DRFLAC_FALSE: u32 = 0;
pub const DR_FLAC_BUFFER_SIZE: u32 = 4096;
pub const DRFLAC_METADATA_BLOCK_TYPE_STREAMINFO: u32 = 0;
pub const DRFLAC_METADATA_BLOCK_TYPE_PADDING: u32 = 1;
pub const DRFLAC_METADATA_BLOCK_TYPE_APPLICATION: u32 = 2;
pub const DRFLAC_METADATA_BLOCK_TYPE_SEEKTABLE: u32 = 3;
pub const DRFLAC_METADATA_BLOCK_TYPE_VORBIS_COMMENT: u32 = 4;
pub const DRFLAC_METADATA_BLOCK_TYPE_CUESHEET: u32 = 5;
pub const DRFLAC_METADATA_BLOCK_TYPE_PICTURE: u32 = 6;
pub const DRFLAC_METADATA_BLOCK_TYPE_INVALID: u32 = 127;
pub const DRFLAC_PICTURE_TYPE_OTHER: u32 = 0;
pub const DRFLAC_PICTURE_TYPE_FILE_ICON: u32 = 1;
pub const DRFLAC_PICTURE_TYPE_OTHER_FILE_ICON: u32 = 2;
pub const DRFLAC_PICTURE_TYPE_COVER_FRONT: u32 = 3;
pub const DRFLAC_PICTURE_TYPE_COVER_BACK: u32 = 4;
pub const DRFLAC_PICTURE_TYPE_LEAFLET_PAGE: u32 = 5;
pub const DRFLAC_PICTURE_TYPE_MEDIA: u32 = 6;
pub const DRFLAC_PICTURE_TYPE_LEAD_ARTIST: u32 = 7;
pub const DRFLAC_PICTURE_TYPE_ARTIST: u32 = 8;
pub const DRFLAC_PICTURE_TYPE_CONDUCTOR: u32 = 9;
pub const DRFLAC_PICTURE_TYPE_BAND: u32 = 10;
pub const DRFLAC_PICTURE_TYPE_COMPOSER: u32 = 11;
pub const DRFLAC_PICTURE_TYPE_LYRICIST: u32 = 12;
pub const DRFLAC_PICTURE_TYPE_RECORDING_LOCATION: u32 = 13;
pub const DRFLAC_PICTURE_TYPE_DURING_RECORDING: u32 = 14;
pub const DRFLAC_PICTURE_TYPE_DURING_PERFORMANCE: u32 = 15;
pub const DRFLAC_PICTURE_TYPE_SCREEN_CAPTURE: u32 = 16;
pub const DRFLAC_PICTURE_TYPE_BRIGHT_COLORED_FISH: u32 = 17;
pub const DRFLAC_PICTURE_TYPE_ILLUSTRATION: u32 = 18;
pub const DRFLAC_PICTURE_TYPE_BAND_LOGOTYPE: u32 = 19;
pub const DRFLAC_PICTURE_TYPE_PUBLISHER_LOGOTYPE: u32 = 20;
pub type wchar_t = cty::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: cty::c_longlong,
    pub __clang_max_align_nonce2: f64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::core::mem::size_of::<max_align_t>() - 16usize];
    ["Alignment of max_align_t"][::core::mem::align_of::<max_align_t>() - 8usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::core::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::core::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 8usize];
};
pub type drflac_int8 = cty::c_schar;
pub type drflac_uint8 = cty::c_uchar;
pub type drflac_int16 = cty::c_short;
pub type drflac_uint16 = cty::c_ushort;
pub type drflac_int32 = cty::c_int;
pub type drflac_uint32 = cty::c_uint;
pub type drflac_int64 = cty::c_longlong;
pub type drflac_uint64 = cty::c_ulonglong;
pub type drflac_uintptr = drflac_uint32;
pub type drflac_bool8 = drflac_uint8;
pub type drflac_bool32 = drflac_uint32;
unsafe extern "C" {
    pub fn drflac_version(
        pMajor: *mut drflac_uint32,
        pMinor: *mut drflac_uint32,
        pRevision: *mut drflac_uint32,
    );
}
unsafe extern "C" {
    pub fn drflac_version_string() -> *const cty::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_allocation_callbacks {
    pub pUserData: *mut cty::c_void,
    pub onMalloc: ::core::option::Option<
        unsafe extern "C" fn(sz: usize, pUserData: *mut cty::c_void) -> *mut cty::c_void,
    >,
    pub onRealloc: ::core::option::Option<
        unsafe extern "C" fn(
            p: *mut cty::c_void,
            sz: usize,
            pUserData: *mut cty::c_void,
        ) -> *mut cty::c_void,
    >,
    pub onFree: ::core::option::Option<
        unsafe extern "C" fn(p: *mut cty::c_void, pUserData: *mut cty::c_void),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_allocation_callbacks"]
        [::core::mem::size_of::<drflac_allocation_callbacks>() - 16usize];
    ["Alignment of drflac_allocation_callbacks"]
        [::core::mem::align_of::<drflac_allocation_callbacks>() - 4usize];
    ["Offset of field: drflac_allocation_callbacks::pUserData"]
        [::core::mem::offset_of!(drflac_allocation_callbacks, pUserData) - 0usize];
    ["Offset of field: drflac_allocation_callbacks::onMalloc"]
        [::core::mem::offset_of!(drflac_allocation_callbacks, onMalloc) - 4usize];
    ["Offset of field: drflac_allocation_callbacks::onRealloc"]
        [::core::mem::offset_of!(drflac_allocation_callbacks, onRealloc) - 8usize];
    ["Offset of field: drflac_allocation_callbacks::onFree"]
        [::core::mem::offset_of!(drflac_allocation_callbacks, onFree) - 12usize];
};
pub type drflac_cache_t = drflac_uint32;
pub const drflac_container_drflac_container_native: drflac_container = 0;
pub const drflac_container_drflac_container_ogg: drflac_container = 1;
pub const drflac_container_drflac_container_unknown: drflac_container = 2;
pub type drflac_container = cty::c_uint;
pub const drflac_seek_origin_DRFLAC_SEEK_SET: drflac_seek_origin = 0;
pub const drflac_seek_origin_DRFLAC_SEEK_CUR: drflac_seek_origin = 1;
pub const drflac_seek_origin_DRFLAC_SEEK_END: drflac_seek_origin = 2;
pub type drflac_seek_origin = cty::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_seekpoint {
    pub firstPCMFrame: drflac_uint64,
    pub flacFrameOffset: drflac_uint64,
    pub pcmFrameCount: drflac_uint16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_seekpoint"][::core::mem::size_of::<drflac_seekpoint>() - 24usize];
    ["Alignment of drflac_seekpoint"][::core::mem::align_of::<drflac_seekpoint>() - 8usize];
    ["Offset of field: drflac_seekpoint::firstPCMFrame"]
        [::core::mem::offset_of!(drflac_seekpoint, firstPCMFrame) - 0usize];
    ["Offset of field: drflac_seekpoint::flacFrameOffset"]
        [::core::mem::offset_of!(drflac_seekpoint, flacFrameOffset) - 8usize];
    ["Offset of field: drflac_seekpoint::pcmFrameCount"]
        [::core::mem::offset_of!(drflac_seekpoint, pcmFrameCount) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_streaminfo {
    pub minBlockSizeInPCMFrames: drflac_uint16,
    pub maxBlockSizeInPCMFrames: drflac_uint16,
    pub minFrameSizeInPCMFrames: drflac_uint32,
    pub maxFrameSizeInPCMFrames: drflac_uint32,
    pub sampleRate: drflac_uint32,
    pub channels: drflac_uint8,
    pub bitsPerSample: drflac_uint8,
    pub totalPCMFrameCount: drflac_uint64,
    pub md5: [drflac_uint8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_streaminfo"][::core::mem::size_of::<drflac_streaminfo>() - 48usize];
    ["Alignment of drflac_streaminfo"][::core::mem::align_of::<drflac_streaminfo>() - 8usize];
    ["Offset of field: drflac_streaminfo::minBlockSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac_streaminfo, minBlockSizeInPCMFrames) - 0usize];
    ["Offset of field: drflac_streaminfo::maxBlockSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac_streaminfo, maxBlockSizeInPCMFrames) - 2usize];
    ["Offset of field: drflac_streaminfo::minFrameSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac_streaminfo, minFrameSizeInPCMFrames) - 4usize];
    ["Offset of field: drflac_streaminfo::maxFrameSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac_streaminfo, maxFrameSizeInPCMFrames) - 8usize];
    ["Offset of field: drflac_streaminfo::sampleRate"]
        [::core::mem::offset_of!(drflac_streaminfo, sampleRate) - 12usize];
    ["Offset of field: drflac_streaminfo::channels"]
        [::core::mem::offset_of!(drflac_streaminfo, channels) - 16usize];
    ["Offset of field: drflac_streaminfo::bitsPerSample"]
        [::core::mem::offset_of!(drflac_streaminfo, bitsPerSample) - 17usize];
    ["Offset of field: drflac_streaminfo::totalPCMFrameCount"]
        [::core::mem::offset_of!(drflac_streaminfo, totalPCMFrameCount) - 24usize];
    ["Offset of field: drflac_streaminfo::md5"]
        [::core::mem::offset_of!(drflac_streaminfo, md5) - 32usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct drflac_metadata {
    pub type_: drflac_uint32,
    pub rawDataSize: drflac_uint32,
    pub rawDataOffset: drflac_uint64,
    pub pRawData: *const cty::c_void,
    pub data: drflac_metadata__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union drflac_metadata__bindgen_ty_1 {
    pub streaminfo: drflac_streaminfo,
    pub padding: drflac_metadata__bindgen_ty_1__bindgen_ty_1,
    pub application: drflac_metadata__bindgen_ty_1__bindgen_ty_2,
    pub seektable: drflac_metadata__bindgen_ty_1__bindgen_ty_3,
    pub vorbis_comment: drflac_metadata__bindgen_ty_1__bindgen_ty_4,
    pub cuesheet: drflac_metadata__bindgen_ty_1__bindgen_ty_5,
    pub picture: drflac_metadata__bindgen_ty_1__bindgen_ty_6,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_1 {
    pub unused: cty::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_1"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_1::unused"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_1, unused) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_2 {
    pub id: drflac_uint32,
    pub pData: *const cty::c_void,
    pub dataSize: drflac_uint32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_2>() - 12usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_2"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_2::id"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_2, id) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_2::pData"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_2, pData) - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_2::dataSize"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_2, dataSize) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_3 {
    pub seekpointCount: drflac_uint32,
    pub pSeekpoints: *const drflac_seekpoint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_3"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_3>() - 8usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_3"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_3>() - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_3::seekpointCount"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_3,
        seekpointCount
    ) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_3::pSeekpoints"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_3,
        pSeekpoints
    ) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_4 {
    pub vendorLength: drflac_uint32,
    pub vendor: *const cty::c_char,
    pub commentCount: drflac_uint32,
    pub pComments: *const cty::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_4"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_4>() - 16usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_4"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_4>() - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_4::vendorLength"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_4,
        vendorLength
    ) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_4::vendor"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_4, vendor) - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_4::commentCount"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_4,
        commentCount
    ) - 8usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_4::pComments"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_4, pComments) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_5 {
    pub catalog: [cty::c_char; 128usize],
    pub leadInSampleCount: drflac_uint64,
    pub isCD: drflac_bool32,
    pub trackCount: drflac_uint8,
    pub pTrackData: *const cty::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_5"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_5>() - 152usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_5"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_5>() - 8usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_5::catalog"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_5, catalog) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_5::leadInSampleCount"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_5,
        leadInSampleCount
    )
        - 128usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_5::isCD"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_5, isCD) - 136usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_5::trackCount"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_5,
        trackCount
    ) - 140usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_5::pTrackData"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_5,
        pTrackData
    ) - 144usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_metadata__bindgen_ty_1__bindgen_ty_6 {
    pub type_: drflac_uint32,
    pub mimeLength: drflac_uint32,
    pub mime: *const cty::c_char,
    pub descriptionLength: drflac_uint32,
    pub description: *const cty::c_char,
    pub width: drflac_uint32,
    pub height: drflac_uint32,
    pub colorDepth: drflac_uint32,
    pub indexColorCount: drflac_uint32,
    pub pictureDataSize: drflac_uint32,
    pub pictureDataOffset: drflac_uint64,
    pub pPictureData: *const drflac_uint8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1__bindgen_ty_6"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_6>() - 56usize];
    ["Alignment of drflac_metadata__bindgen_ty_1__bindgen_ty_6"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1__bindgen_ty_6>() - 8usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::type_"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_6, type_) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::mimeLength"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_6, mimeLength) - 4usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::mime"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_6, mime) - 8usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::descriptionLength"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        descriptionLength
    )
        - 12usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::description"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        description
    ) - 16usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::width"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_6, width) - 20usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::height"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1__bindgen_ty_6, height) - 24usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::colorDepth"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        colorDepth
    ) - 28usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::indexColorCount"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        indexColorCount
    ) - 32usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::pictureDataSize"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        pictureDataSize
    ) - 36usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::pictureDataOffset"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        pictureDataOffset
    )
        - 40usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1__bindgen_ty_6::pPictureData"][::core::mem::offset_of!(
        drflac_metadata__bindgen_ty_1__bindgen_ty_6,
        pPictureData
    ) - 48usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata__bindgen_ty_1"]
        [::core::mem::size_of::<drflac_metadata__bindgen_ty_1>() - 152usize];
    ["Alignment of drflac_metadata__bindgen_ty_1"]
        [::core::mem::align_of::<drflac_metadata__bindgen_ty_1>() - 8usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::streaminfo"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, streaminfo) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::padding"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, padding) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::application"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, application) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::seektable"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, seektable) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::vorbis_comment"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, vorbis_comment) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::cuesheet"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, cuesheet) - 0usize];
    ["Offset of field: drflac_metadata__bindgen_ty_1::picture"]
        [::core::mem::offset_of!(drflac_metadata__bindgen_ty_1, picture) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_metadata"][::core::mem::size_of::<drflac_metadata>() - 176usize];
    ["Alignment of drflac_metadata"][::core::mem::align_of::<drflac_metadata>() - 8usize];
    ["Offset of field: drflac_metadata::type_"]
        [::core::mem::offset_of!(drflac_metadata, type_) - 0usize];
    ["Offset of field: drflac_metadata::rawDataSize"]
        [::core::mem::offset_of!(drflac_metadata, rawDataSize) - 4usize];
    ["Offset of field: drflac_metadata::rawDataOffset"]
        [::core::mem::offset_of!(drflac_metadata, rawDataOffset) - 8usize];
    ["Offset of field: drflac_metadata::pRawData"]
        [::core::mem::offset_of!(drflac_metadata, pRawData) - 16usize];
    ["Offset of field: drflac_metadata::data"]
        [::core::mem::offset_of!(drflac_metadata, data) - 24usize];
};
pub type drflac_read_proc = ::core::option::Option<
    unsafe extern "C" fn(
        pUserData: *mut cty::c_void,
        pBufferOut: *mut cty::c_void,
        bytesToRead: usize,
    ) -> usize,
>;
pub type drflac_seek_proc = ::core::option::Option<
    unsafe extern "C" fn(
        pUserData: *mut cty::c_void,
        offset: cty::c_int,
        origin: drflac_seek_origin,
    ) -> drflac_bool32,
>;
pub type drflac_tell_proc = ::core::option::Option<
    unsafe extern "C" fn(pUserData: *mut cty::c_void, pCursor: *mut drflac_int64) -> drflac_bool32,
>;
pub type drflac_meta_proc = ::core::option::Option<
    unsafe extern "C" fn(pUserData: *mut cty::c_void, pMetadata: *mut drflac_metadata),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac__memory_stream {
    pub data: *const drflac_uint8,
    pub dataSize: usize,
    pub currentReadPos: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac__memory_stream"][::core::mem::size_of::<drflac__memory_stream>() - 12usize];
    ["Alignment of drflac__memory_stream"]
        [::core::mem::align_of::<drflac__memory_stream>() - 4usize];
    ["Offset of field: drflac__memory_stream::data"]
        [::core::mem::offset_of!(drflac__memory_stream, data) - 0usize];
    ["Offset of field: drflac__memory_stream::dataSize"]
        [::core::mem::offset_of!(drflac__memory_stream, dataSize) - 4usize];
    ["Offset of field: drflac__memory_stream::currentReadPos"]
        [::core::mem::offset_of!(drflac__memory_stream, currentReadPos) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_bs {
    pub onRead: drflac_read_proc,
    pub onSeek: drflac_seek_proc,
    pub onTell: drflac_tell_proc,
    pub pUserData: *mut cty::c_void,
    pub unalignedByteCount: usize,
    pub unalignedCache: drflac_cache_t,
    pub nextL2Line: drflac_uint32,
    pub consumedBits: drflac_uint32,
    pub cacheL2: [drflac_cache_t; 1024usize],
    pub cache: drflac_cache_t,
    pub crc16: drflac_uint16,
    pub crc16Cache: drflac_cache_t,
    pub crc16CacheIgnoredBytes: drflac_uint32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_bs"][::core::mem::size_of::<drflac_bs>() - 4144usize];
    ["Alignment of drflac_bs"][::core::mem::align_of::<drflac_bs>() - 4usize];
    ["Offset of field: drflac_bs::onRead"][::core::mem::offset_of!(drflac_bs, onRead) - 0usize];
    ["Offset of field: drflac_bs::onSeek"][::core::mem::offset_of!(drflac_bs, onSeek) - 4usize];
    ["Offset of field: drflac_bs::onTell"][::core::mem::offset_of!(drflac_bs, onTell) - 8usize];
    ["Offset of field: drflac_bs::pUserData"]
        [::core::mem::offset_of!(drflac_bs, pUserData) - 12usize];
    ["Offset of field: drflac_bs::unalignedByteCount"]
        [::core::mem::offset_of!(drflac_bs, unalignedByteCount) - 16usize];
    ["Offset of field: drflac_bs::unalignedCache"]
        [::core::mem::offset_of!(drflac_bs, unalignedCache) - 20usize];
    ["Offset of field: drflac_bs::nextL2Line"]
        [::core::mem::offset_of!(drflac_bs, nextL2Line) - 24usize];
    ["Offset of field: drflac_bs::consumedBits"]
        [::core::mem::offset_of!(drflac_bs, consumedBits) - 28usize];
    ["Offset of field: drflac_bs::cacheL2"][::core::mem::offset_of!(drflac_bs, cacheL2) - 32usize];
    ["Offset of field: drflac_bs::cache"][::core::mem::offset_of!(drflac_bs, cache) - 4128usize];
    ["Offset of field: drflac_bs::crc16"][::core::mem::offset_of!(drflac_bs, crc16) - 4132usize];
    ["Offset of field: drflac_bs::crc16Cache"]
        [::core::mem::offset_of!(drflac_bs, crc16Cache) - 4136usize];
    ["Offset of field: drflac_bs::crc16CacheIgnoredBytes"]
        [::core::mem::offset_of!(drflac_bs, crc16CacheIgnoredBytes) - 4140usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_subframe {
    pub subframeType: drflac_uint8,
    pub wastedBitsPerSample: drflac_uint8,
    pub lpcOrder: drflac_uint8,
    pub pSamplesS32: *mut drflac_int32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_subframe"][::core::mem::size_of::<drflac_subframe>() - 8usize];
    ["Alignment of drflac_subframe"][::core::mem::align_of::<drflac_subframe>() - 4usize];
    ["Offset of field: drflac_subframe::subframeType"]
        [::core::mem::offset_of!(drflac_subframe, subframeType) - 0usize];
    ["Offset of field: drflac_subframe::wastedBitsPerSample"]
        [::core::mem::offset_of!(drflac_subframe, wastedBitsPerSample) - 1usize];
    ["Offset of field: drflac_subframe::lpcOrder"]
        [::core::mem::offset_of!(drflac_subframe, lpcOrder) - 2usize];
    ["Offset of field: drflac_subframe::pSamplesS32"]
        [::core::mem::offset_of!(drflac_subframe, pSamplesS32) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_frame_header {
    pub pcmFrameNumber: drflac_uint64,
    pub flacFrameNumber: drflac_uint32,
    pub sampleRate: drflac_uint32,
    pub blockSizeInPCMFrames: drflac_uint16,
    pub channelAssignment: drflac_uint8,
    pub bitsPerSample: drflac_uint8,
    pub crc8: drflac_uint8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_frame_header"][::core::mem::size_of::<drflac_frame_header>() - 24usize];
    ["Alignment of drflac_frame_header"][::core::mem::align_of::<drflac_frame_header>() - 8usize];
    ["Offset of field: drflac_frame_header::pcmFrameNumber"]
        [::core::mem::offset_of!(drflac_frame_header, pcmFrameNumber) - 0usize];
    ["Offset of field: drflac_frame_header::flacFrameNumber"]
        [::core::mem::offset_of!(drflac_frame_header, flacFrameNumber) - 8usize];
    ["Offset of field: drflac_frame_header::sampleRate"]
        [::core::mem::offset_of!(drflac_frame_header, sampleRate) - 12usize];
    ["Offset of field: drflac_frame_header::blockSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac_frame_header, blockSizeInPCMFrames) - 16usize];
    ["Offset of field: drflac_frame_header::channelAssignment"]
        [::core::mem::offset_of!(drflac_frame_header, channelAssignment) - 18usize];
    ["Offset of field: drflac_frame_header::bitsPerSample"]
        [::core::mem::offset_of!(drflac_frame_header, bitsPerSample) - 19usize];
    ["Offset of field: drflac_frame_header::crc8"]
        [::core::mem::offset_of!(drflac_frame_header, crc8) - 20usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_frame {
    pub header: drflac_frame_header,
    pub pcmFramesRemaining: drflac_uint32,
    pub subframes: [drflac_subframe; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_frame"][::core::mem::size_of::<drflac_frame>() - 96usize];
    ["Alignment of drflac_frame"][::core::mem::align_of::<drflac_frame>() - 8usize];
    ["Offset of field: drflac_frame::header"]
        [::core::mem::offset_of!(drflac_frame, header) - 0usize];
    ["Offset of field: drflac_frame::pcmFramesRemaining"]
        [::core::mem::offset_of!(drflac_frame, pcmFramesRemaining) - 24usize];
    ["Offset of field: drflac_frame::subframes"]
        [::core::mem::offset_of!(drflac_frame, subframes) - 28usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac {
    pub onMeta: drflac_meta_proc,
    pub pUserDataMD: *mut cty::c_void,
    pub allocationCallbacks: drflac_allocation_callbacks,
    pub sampleRate: drflac_uint32,
    pub channels: drflac_uint8,
    pub bitsPerSample: drflac_uint8,
    pub maxBlockSizeInPCMFrames: drflac_uint16,
    pub totalPCMFrameCount: drflac_uint64,
    pub container: drflac_container,
    pub seekpointCount: drflac_uint32,
    pub currentFLACFrame: drflac_frame,
    pub currentPCMFrame: drflac_uint64,
    pub firstFLACFramePosInBytes: drflac_uint64,
    pub memoryStream: drflac__memory_stream,
    pub pDecodedSamples: *mut drflac_int32,
    pub pSeekpoints: *mut drflac_seekpoint,
    pub _oggbs: *mut cty::c_void,
    pub _bitfield_align_1: [u8; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
    pub bs: drflac_bs,
    pub pExtraData: [drflac_uint8; 1usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac"][::core::mem::size_of::<drflac>() - 4336usize];
    ["Alignment of drflac"][::core::mem::align_of::<drflac>() - 8usize];
    ["Offset of field: drflac::onMeta"][::core::mem::offset_of!(drflac, onMeta) - 0usize];
    ["Offset of field: drflac::pUserDataMD"][::core::mem::offset_of!(drflac, pUserDataMD) - 4usize];
    ["Offset of field: drflac::allocationCallbacks"]
        [::core::mem::offset_of!(drflac, allocationCallbacks) - 8usize];
    ["Offset of field: drflac::sampleRate"][::core::mem::offset_of!(drflac, sampleRate) - 24usize];
    ["Offset of field: drflac::channels"][::core::mem::offset_of!(drflac, channels) - 28usize];
    ["Offset of field: drflac::bitsPerSample"]
        [::core::mem::offset_of!(drflac, bitsPerSample) - 29usize];
    ["Offset of field: drflac::maxBlockSizeInPCMFrames"]
        [::core::mem::offset_of!(drflac, maxBlockSizeInPCMFrames) - 30usize];
    ["Offset of field: drflac::totalPCMFrameCount"]
        [::core::mem::offset_of!(drflac, totalPCMFrameCount) - 32usize];
    ["Offset of field: drflac::container"][::core::mem::offset_of!(drflac, container) - 40usize];
    ["Offset of field: drflac::seekpointCount"]
        [::core::mem::offset_of!(drflac, seekpointCount) - 44usize];
    ["Offset of field: drflac::currentFLACFrame"]
        [::core::mem::offset_of!(drflac, currentFLACFrame) - 48usize];
    ["Offset of field: drflac::currentPCMFrame"]
        [::core::mem::offset_of!(drflac, currentPCMFrame) - 144usize];
    ["Offset of field: drflac::firstFLACFramePosInBytes"]
        [::core::mem::offset_of!(drflac, firstFLACFramePosInBytes) - 152usize];
    ["Offset of field: drflac::memoryStream"]
        [::core::mem::offset_of!(drflac, memoryStream) - 160usize];
    ["Offset of field: drflac::pDecodedSamples"]
        [::core::mem::offset_of!(drflac, pDecodedSamples) - 172usize];
    ["Offset of field: drflac::pSeekpoints"]
        [::core::mem::offset_of!(drflac, pSeekpoints) - 176usize];
    ["Offset of field: drflac::_oggbs"][::core::mem::offset_of!(drflac, _oggbs) - 180usize];
    ["Offset of field: drflac::bs"][::core::mem::offset_of!(drflac, bs) - 188usize];
    ["Offset of field: drflac::pExtraData"]
        [::core::mem::offset_of!(drflac, pExtraData) - 4332usize];
};
impl drflac {
    #[inline]
    pub fn _noSeekTableSeek(&self) -> drflac_bool32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(0usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set__noSeekTableSeek(&mut self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(0usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn _noSeekTableSeek_raw(this: *const Self) -> drflac_bool32 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                0usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set__noSeekTableSeek_raw(this: *mut Self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                0usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn _noBinarySearchSeek(&self) -> drflac_bool32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(1usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set__noBinarySearchSeek(&mut self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(1usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn _noBinarySearchSeek_raw(this: *const Self) -> drflac_bool32 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                1usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set__noBinarySearchSeek_raw(this: *mut Self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                1usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn _noBruteForceSeek(&self) -> drflac_bool32 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get(2usize, 1u8) as u32) }
    }
    #[inline]
    pub fn set__noBruteForceSeek(&mut self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            self._bitfield_1.set(2usize, 1u8, val as u64)
        }
    }
    #[inline]
    pub unsafe fn _noBruteForceSeek_raw(this: *const Self) -> drflac_bool32 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 1usize]>>::raw_get(
                ::core::ptr::addr_of!((*this)._bitfield_1),
                2usize,
                1u8,
            ) as u32)
        }
    }
    #[inline]
    pub unsafe fn set__noBruteForceSeek_raw(this: *mut Self, val: drflac_bool32) {
        unsafe {
            let val: u32 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 1usize]>>::raw_set(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                2usize,
                1u8,
                val as u64,
            )
        }
    }
    #[inline]
    pub fn new_bitfield_1(
        _noSeekTableSeek: drflac_bool32,
        _noBinarySearchSeek: drflac_bool32,
        _noBruteForceSeek: drflac_bool32,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit.set(0usize, 1u8, {
            let _noSeekTableSeek: u32 = unsafe { ::core::mem::transmute(_noSeekTableSeek) };
            _noSeekTableSeek as u64
        });
        __bindgen_bitfield_unit.set(1usize, 1u8, {
            let _noBinarySearchSeek: u32 = unsafe { ::core::mem::transmute(_noBinarySearchSeek) };
            _noBinarySearchSeek as u64
        });
        __bindgen_bitfield_unit.set(2usize, 1u8, {
            let _noBruteForceSeek: u32 = unsafe { ::core::mem::transmute(_noBruteForceSeek) };
            _noBruteForceSeek as u64
        });
        __bindgen_bitfield_unit
    }
}
unsafe extern "C" {
    pub fn drflac_open(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_relaxed(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        container: drflac_container,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_with_metadata(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        onMeta: drflac_meta_proc,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_with_metadata_relaxed(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        onMeta: drflac_meta_proc,
        container: drflac_container,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_close(pFlac: *mut drflac);
}
unsafe extern "C" {
    pub fn drflac_read_pcm_frames_s32(
        pFlac: *mut drflac,
        framesToRead: drflac_uint64,
        pBufferOut: *mut drflac_int32,
    ) -> drflac_uint64;
}
unsafe extern "C" {
    pub fn drflac_read_pcm_frames_s16(
        pFlac: *mut drflac,
        framesToRead: drflac_uint64,
        pBufferOut: *mut drflac_int16,
    ) -> drflac_uint64;
}
unsafe extern "C" {
    pub fn drflac_read_pcm_frames_f32(
        pFlac: *mut drflac,
        framesToRead: drflac_uint64,
        pBufferOut: *mut f32,
    ) -> drflac_uint64;
}
unsafe extern "C" {
    pub fn drflac_seek_to_pcm_frame(
        pFlac: *mut drflac,
        pcmFrameIndex: drflac_uint64,
    ) -> drflac_bool32;
}
unsafe extern "C" {
    pub fn drflac_open_file(
        pFileName: *const cty::c_char,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_file_w(
        pFileName: *const wchar_t,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_file_with_metadata(
        pFileName: *const cty::c_char,
        onMeta: drflac_meta_proc,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_file_with_metadata_w(
        pFileName: *const wchar_t,
        onMeta: drflac_meta_proc,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_memory(
        pData: *const cty::c_void,
        dataSize: usize,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_memory_with_metadata(
        pData: *const cty::c_void,
        dataSize: usize,
        onMeta: drflac_meta_proc,
        pUserData: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac;
}
unsafe extern "C" {
    pub fn drflac_open_and_read_pcm_frames_s32(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        pUserData: *mut cty::c_void,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int32;
}
unsafe extern "C" {
    pub fn drflac_open_and_read_pcm_frames_s16(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        pUserData: *mut cty::c_void,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int16;
}
unsafe extern "C" {
    pub fn drflac_open_and_read_pcm_frames_f32(
        onRead: drflac_read_proc,
        onSeek: drflac_seek_proc,
        onTell: drflac_tell_proc,
        pUserData: *mut cty::c_void,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut f32;
}
unsafe extern "C" {
    pub fn drflac_open_file_and_read_pcm_frames_s32(
        filename: *const cty::c_char,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int32;
}
unsafe extern "C" {
    pub fn drflac_open_file_and_read_pcm_frames_s16(
        filename: *const cty::c_char,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int16;
}
unsafe extern "C" {
    pub fn drflac_open_file_and_read_pcm_frames_f32(
        filename: *const cty::c_char,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut f32;
}
unsafe extern "C" {
    pub fn drflac_open_memory_and_read_pcm_frames_s32(
        data: *const cty::c_void,
        dataSize: usize,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int32;
}
unsafe extern "C" {
    pub fn drflac_open_memory_and_read_pcm_frames_s16(
        data: *const cty::c_void,
        dataSize: usize,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut drflac_int16;
}
unsafe extern "C" {
    pub fn drflac_open_memory_and_read_pcm_frames_f32(
        data: *const cty::c_void,
        dataSize: usize,
        channels: *mut cty::c_uint,
        sampleRate: *mut cty::c_uint,
        totalPCMFrameCount: *mut drflac_uint64,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    ) -> *mut f32;
}
unsafe extern "C" {
    pub fn drflac_free(
        p: *mut cty::c_void,
        pAllocationCallbacks: *const drflac_allocation_callbacks,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_vorbis_comment_iterator {
    pub countRemaining: drflac_uint32,
    pub pRunningData: *const cty::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_vorbis_comment_iterator"]
        [::core::mem::size_of::<drflac_vorbis_comment_iterator>() - 8usize];
    ["Alignment of drflac_vorbis_comment_iterator"]
        [::core::mem::align_of::<drflac_vorbis_comment_iterator>() - 4usize];
    ["Offset of field: drflac_vorbis_comment_iterator::countRemaining"]
        [::core::mem::offset_of!(drflac_vorbis_comment_iterator, countRemaining) - 0usize];
    ["Offset of field: drflac_vorbis_comment_iterator::pRunningData"]
        [::core::mem::offset_of!(drflac_vorbis_comment_iterator, pRunningData) - 4usize];
};
unsafe extern "C" {
    pub fn drflac_init_vorbis_comment_iterator(
        pIter: *mut drflac_vorbis_comment_iterator,
        commentCount: drflac_uint32,
        pComments: *const cty::c_void,
    );
}
unsafe extern "C" {
    pub fn drflac_next_vorbis_comment(
        pIter: *mut drflac_vorbis_comment_iterator,
        pCommentLengthOut: *mut drflac_uint32,
    ) -> *const cty::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_cuesheet_track_iterator {
    pub countRemaining: drflac_uint32,
    pub pRunningData: *const cty::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_cuesheet_track_iterator"]
        [::core::mem::size_of::<drflac_cuesheet_track_iterator>() - 8usize];
    ["Alignment of drflac_cuesheet_track_iterator"]
        [::core::mem::align_of::<drflac_cuesheet_track_iterator>() - 4usize];
    ["Offset of field: drflac_cuesheet_track_iterator::countRemaining"]
        [::core::mem::offset_of!(drflac_cuesheet_track_iterator, countRemaining) - 0usize];
    ["Offset of field: drflac_cuesheet_track_iterator::pRunningData"]
        [::core::mem::offset_of!(drflac_cuesheet_track_iterator, pRunningData) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_cuesheet_track_index {
    pub offset: drflac_uint64,
    pub index: drflac_uint8,
    pub reserved: [drflac_uint8; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_cuesheet_track_index"]
        [::core::mem::size_of::<drflac_cuesheet_track_index>() - 16usize];
    ["Alignment of drflac_cuesheet_track_index"]
        [::core::mem::align_of::<drflac_cuesheet_track_index>() - 8usize];
    ["Offset of field: drflac_cuesheet_track_index::offset"]
        [::core::mem::offset_of!(drflac_cuesheet_track_index, offset) - 0usize];
    ["Offset of field: drflac_cuesheet_track_index::index"]
        [::core::mem::offset_of!(drflac_cuesheet_track_index, index) - 8usize];
    ["Offset of field: drflac_cuesheet_track_index::reserved"]
        [::core::mem::offset_of!(drflac_cuesheet_track_index, reserved) - 9usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct drflac_cuesheet_track {
    pub offset: drflac_uint64,
    pub trackNumber: drflac_uint8,
    pub ISRC: [cty::c_char; 12usize],
    pub isAudio: drflac_bool8,
    pub preEmphasis: drflac_bool8,
    pub indexCount: drflac_uint8,
    pub pIndexPoints: *const drflac_cuesheet_track_index,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of drflac_cuesheet_track"][::core::mem::size_of::<drflac_cuesheet_track>() - 32usize];
    ["Alignment of drflac_cuesheet_track"]
        [::core::mem::align_of::<drflac_cuesheet_track>() - 8usize];
    ["Offset of field: drflac_cuesheet_track::offset"]
        [::core::mem::offset_of!(drflac_cuesheet_track, offset) - 0usize];
    ["Offset of field: drflac_cuesheet_track::trackNumber"]
        [::core::mem::offset_of!(drflac_cuesheet_track, trackNumber) - 8usize];
    ["Offset of field: drflac_cuesheet_track::ISRC"]
        [::core::mem::offset_of!(drflac_cuesheet_track, ISRC) - 9usize];
    ["Offset of field: drflac_cuesheet_track::isAudio"]
        [::core::mem::offset_of!(drflac_cuesheet_track, isAudio) - 21usize];
    ["Offset of field: drflac_cuesheet_track::preEmphasis"]
        [::core::mem::offset_of!(drflac_cuesheet_track, preEmphasis) - 22usize];
    ["Offset of field: drflac_cuesheet_track::indexCount"]
        [::core::mem::offset_of!(drflac_cuesheet_track, indexCount) - 23usize];
    ["Offset of field: drflac_cuesheet_track::pIndexPoints"]
        [::core::mem::offset_of!(drflac_cuesheet_track, pIndexPoints) - 24usize];
};
unsafe extern "C" {
    pub fn drflac_init_cuesheet_track_iterator(
        pIter: *mut drflac_cuesheet_track_iterator,
        trackCount: drflac_uint32,
        pTrackData: *const cty::c_void,
    );
}
unsafe extern "C" {
    pub fn drflac_next_cuesheet_track(
        pIter: *mut drflac_cuesheet_track_iterator,
        pCuesheetTrack: *mut drflac_cuesheet_track,
    ) -> drflac_bool32;
}
